language: rust
rust:
  - stable
cache: cargo

addons:
  apt:
    packages:
    - libwebkit2gtk-4.0-dev

before_script: (cargo install rustfmt || true)
script:
- |
  cargo fmt -- --write-mode=diff &&
  cargo build
