[package]
name = "liftinstall"
version = "0.1.0"
authors = ["James <jselby@jselby.net>"]
repository = "https://github.com/j-selby/liftinstall.git"
documentation = "https://liftinstall.jselby.net"
description = "An adaptable installer for your application."

[dependencies]
web-view = {git = "https://github.com/Boscop/web-view.git", rev = "3932662"}

hyper = "0.11.15"
hyper-tls = "0.1.2"
tokio-core = "*"
futures = "*"
mime_guess = "1.8.3"
url = "*"

reqwest = "0.8.4"
number_prefix = "0.2.7"

phf = "0.7.22"
phf_macros = "0.7.22"

serde = "1.0.27"
serde_derive = "1.0.27"
serde_json = "1.0.9"

toml = "0.4"

nfd = "0.0.4"

semver = {version = "0.9.0", features = ["serde"]}
regex = "0.2"

zip = "0.2.8"
