[package]
name = "yuzu-installer"
version = "0.1.0"
authors = ["James <jselby@jselby.net>"]

[dependencies]
web-view = "0.1.2"

hyper = "0.11.15"
hyper-tls = "0.1.2"
tokio-core = "*"
futures = "*"
mime_guess = "1.8.3"
url = "*"

reqwest = "0.8.4"
number_prefix = "0.2.7"

includedir = "0.2.2"
phf = "0.7.21"

serde = "1.0.27"
serde_derive = "1.0.27"
serde_json = "1.0.9"

toml = "0.4"

nfd = "0.0.4"

semver = "0.9.0"
regex = "0.2"

[build-dependencies]
includedir_codegen = "0.2.0"
