[package]
name = "yuzu-installer"
version = "0.1.0"
authors = ["James <jselby@jselby.net>"]

[dependencies]
web-view = "0.1.2"

hyper = "0.11.15"
hyper-tls = "0.1.2"
tokio-core = "*"
futures = "*"
mime_guess = "1.8.3"
url = "*"

reqwest = "0.8.4"
number_prefix = "0.2.7"

includedir = {git = "https://github.com/j-selby/includedir.git", rev="4e25ad8"}
phf = "0.7.21"

serde = "1.0.27"
serde_derive = "1.0.27"
serde_json = "1.0.9"

toml = "0.4"

nfd = "0.0.4"

semver = {version = "0.9.0", features = ["serde"]}
regex = "0.2"

zip = "0.2.8"

[build-dependencies]
includedir_codegen = {git = "https://github.com/j-selby/includedir.git", rev="e6db212"}
